### ISSUE TITLE
 code problem

### ISSUE THREAD

**Issue by huiwudiyi** [bioannidis/adaptive_recurrent_graph_neural_network#1]
Thanks for your contribution。
Recently，I have  read the papper and  code. I have some questions: In the papper ,you deal with mul-relation data，but i don't understand how your code perform mul-relation data embedding

**Comment by xuesanshi** [comment]
Are you Chinese? Can we add a friend to share this article? I am also reading this article.

**Comment by huiwudiyi** [comment]
> Are you Chinese? Can we add a friend to share this article? I am also reading this article.

 yes！ my email address : zachary6chu@gmail.com
